name: Jojo's CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.cs"

jobs:
  build:
    name: Build and Test (.NET ${{ matrix.dotnet-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubunto-latest", "windows-latest"]
        dotnet-version: ["8.0.x", "9.0.x"]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: Print runner context
        run: echo '${{ toJson(runner) }}'

      - name: Print GitHub context
        run: echo '${{ toJson(github) }}'

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        run: dotnet build

      - name: Run tests
        if: success()
        run: dotnet test

      - name: Build and test result
        if: success()
        shell: bash
        run: |
          echo "âœ… Build and tests passed with .NET version ${{ matrix.dotnet-version }}!"
          echo "   Triggered by: ${{ github.actor }}"
          echo "   Event: ${{ github.event_name }}"
